### ISSUE TITLE
The carrier should be attached to the busses and not to the components

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/oemof-tabular-plugins#26]
## Description of the issue

When component have only one input and/or one output, it is straightforward to infer what is the carrier of each bus.
Right now it is done via the "bus" and "from_bus" fields of the resources (i.e. the carrier of the component is assigned to the bus provided under the column "bus" or "from_bus" of the component)

Each bus should be assigned to one and only one carrier. However if we include the `oemof.industry.MIMO` we now have "from_bus_0" and "from_bus_0". 

In our example the MIMO component only has one carrier, "water", and two in busses "bus_water" and "bus_elec".
This leads that the fonction inferring the carrier of the busses would like to do the following mapping:
```
"bus_water": "water"
"bus_elec": "water"
``` 
But, as "bus_elec" is already associated to "electricity" it leads to an error.

## Ideas of solution
Assign the carrier to the busses will solve this issue and will also allow more refined result analysis for sector-coupling indicators as more than one carrier can be associated to a component with multiple inputs/outputs

**Comment by Bachibouzouk** [comment]
@henhuy - what do you think about this?

**Comment by henhuy** [comment]
I'm not using carrier or tech attributes - would do that always in postprocessing.
But I can understand your problem and your suggestion sounds reasonable.

**Comment by Emm-Zett** [comment]
I am an oemof-beginner, but in my current energy system (where we dont care about an actual grid) every bus is one carrier, so in that case I am already using bus/carrier like this.
And even if a grid is to be modelled, I think it makes perfectly sense, to assign carriers to busses, not components.
One difficulty (with tabular postprocessing) that could arise, may be dispatchables, that only connect to an output bus.
